version: "3.8"

services:
  db:
    container_name: mysql
    image: mariadb:11.2.3
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    restart: unless-stopped
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - connection

  app:
    container_name: ghepa
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      APP_HOST: ${APP_HOST}
      APP_PORT: ${APP_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    networks:
      - connection

networks:
  connection:
    driver: bridge
